services:
  maria_db:
    image: mariadb:11.4-rc-jammy
    container_name: mariadb_mars
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mars
      #MYSQL_USER: myuser
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
