services:
  mysql:
    image: mysql:9.3.0-oraclelinux9
    container_name: mysql_mars
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mars
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
